### ISSUE TITLE
Questioning documentation on breakdown & stripboard array lengths

### ISSUE THREAD

**Issue by ldeboer** [UniversalScheduleStandard/UniversalScheduleStandard#6]
I have a question on this specific section of the documentation, which is found under the header **[Board Objects](https://github.com/UniversalScheduleStandard/UniversalScheduleStandard/blob/main/docs/docs.md#board-objects)**: 

_"The length of the combined arrays of the breakdownIds across all boards within a stripboard object must be equal to the total number of breakdown objects in breakdowns. For example, say you have two boards -- 'stripboard' which has 75 IDs and 'boneyard' which has 25 IDs -- you must have a total of 100 breakdown objects in your breakdowns array. [Breakdown objects](https://github.com/UniversalScheduleStandard/UniversalScheduleStandard/blob/main/docs/docs.md#breakdown-objects) that are not referenced in a boards.breakdownIds array will be ignored."_

I'm curious how this rule applies when having multiple stripboard versions. For instance, what if I had one board that was 1st unit, one board that was 2nd unit, add another board that was an alternate schedule version that I want to have saved as a backup. Between these three boards, it's very likely that some scenes would be listed on multiple strip boards. (For instance, my alternate schedule version might contain many of the same scenes as my first unit schedule, but in a slightly rearranged order.)
 
In such a case, the rule above which states that the total sum length of both arrays should be equal would not apply. I might be missing something in the way I'm interpreting this, but I wanted to double-check. Thanks!

Luke @ SetHero ([luke@setheroapp.com](mailto:luke@setheroapp.com))

**Comment by modemmute** [comment]
Ah, thanks for bringing this up. I think I should further clarify the meaning of that paragraph in the docs. 

A stripboard represents one complete scenario for the film. Each stripboard contains a number of different boards. Those boards can represent different areas of responsibility for each strip - such as multiple units, or a boneyard for strips that won't be shot. All breakdowns must exist in only one board, as there can't be two areas of responsibility for one breakdown. (In the case of parted scenes, such as two sides of a phone call, those should be split into two different breakdowns).

In your example you want to create a separate scenario, which is commonly done during scheduling. This would be accomplished by creating a new stripboard and thus new boards. In this second scenario, the breakdowns could be assigned different units than they are in the first scenario. You could even have some breakdowns that were to be shot in the first scenario in the boneyard of the second scenario. But the total sum of the breakdowns in every stripboard must equal the total sum of breakdown objects in the schedule. Otherwise you could potentially end up with scenarios where scenes were missing. 

I will update the docs to further clarify the point - maybe even add a graphic to illustrate. Will also leave this issue open for the time being in case anyone else has any further points to make on this topic. 

Thanks!

**Comment by UniversalScheduleStandard** [comment]
This suggestion was accepted and is included in v0.9.1
